import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.cli.help_format import build_standard_parser
from src.config.loader import load_json
from src.forensics.volatility import VolatilityRunner
from src.labels.intersection import build_label_from_intersection, write_label_file


def _read_json(path: str) -> Any:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _family_candidates(
    snapshot_row: Dict[str, Any],
    family_to_processes: Dict[str, List[str]],
    default_candidates: List[str],
) -> List[str]:
    family = str(snapshot_row.get("executable", "Unknown")).strip()
    if family in family_to_processes:
        return list(family_to_processes[family])

    # Try case-insensitive match.
    lower_map = {k.lower(): v for k, v in family_to_processes.items()}
    return list(lower_map.get(family.lower(), default_candidates))


if __name__ == "__main__":
    load_dotenv()

    parser = build_standard_parser(
        prog="build_labels_intersection.py",
        description="Build per-snapshot label files using process-name intersection against pslist output.",
        examples=[
            "python scripts/build_labels_intersection.py --config config/config.json --manifest results/snapshot_manifest.json --ground-truth-config config/ground_truth_process_names.json --out-dir results/labels",
        ],
    )
    parser.add_argument("--config", default="config/config.json", help="Base config JSON")
    parser.add_argument(
        "--manifest",
        default="results/snapshot_manifest.json",
        help="Snapshot manifest JSON generated by build_snapshot_manifest",
    )
    parser.add_argument(
        "--ground-truth-config",
        default="config/ground_truth_process_names.json",
        help="Family to runtime-candidate process names JSON",
    )
    parser.add_argument(
        "--category",
        default="all",
        choices=["all", "benign", "ransomware", "benign-tool", "unknown"],
        help="Only generate labels for selected category",
    )
    parser.add_argument("--limit", type=int, default=0, help="Max snapshots to process (0 = all)")
    parser.add_argument(
        "--out-dir",
        default="results/labels",
        help="Directory to write per-snapshot label JSON files",
    )
    parser.add_argument(
        "--summary-json",
        default="results/labels/labels_summary.json",
        help="Summary JSON path",
    )
    args = parser.parse_args()

    cfg = load_json(args.config)
    manifest = _read_json(args.manifest)
    gt_cfg = _read_json(args.ground_truth_config)

    family_to_processes = gt_cfg.get("family_process_names", {})
    default_candidates = gt_cfg.get("default_candidates", [])

    selected = []
    for row in manifest:
        cat = str(row.get("category", "unknown"))
        if args.category != "all" and cat != args.category:
            continue
        selected.append(row)

    if args.limit > 0:
        selected = selected[: args.limit]

    volatility = VolatilityRunner(
        cfg["volatility_script_path"],
        plugin_timeout_seconds=cfg.get("volatility_plugin_timeout_seconds"),
    )

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    summary = {
        "total_selected": len(selected),
        "processed": 0,
        "failed": 0,
        "items": [],
    }

    for row in selected:
        snapshot_name = str(row.get("file_name"))
        snapshot_stem = Path(snapshot_name).stem
        family = str(row.get("executable", "Unknown"))
        dump_path = str(row.get("file_path"))

        item = {
            "snapshot": snapshot_name,
            "family": family,
            "dump_path": dump_path,
            "label_path": str(out_dir / f"{snapshot_stem}.labels.json"),
            "status": "ok",
            "error": None,
        }

        try:
            pslist_output = volatility.run_plugin(dump_path, "windows.pslist")
            candidates = _family_candidates(row, family_to_processes, default_candidates)
            label = build_label_from_intersection(pslist_output, candidates, family, snapshot_name)
            write_label_file(label, item["label_path"])
            item["malicious_count"] = len(label.get("malicious_pids", []))
            item["all_count"] = len(label.get("all_pids", []))
            summary["processed"] += 1
        except Exception as e:  # noqa: BLE001
            item["status"] = "error"
            item["error"] = str(e)
            summary["failed"] += 1

        summary["items"].append(item)

    summary_path = Path(args.summary_json)
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(json.dumps(summary, ensure_ascii=True, indent=2), encoding="utf-8")

    print(json.dumps({
        "total_selected": summary["total_selected"],
        "processed": summary["processed"],
        "failed": summary["failed"],
        "summary_json": str(summary_path),
    }, ensure_ascii=True, indent=2))